config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  get '/emergencies/get_routes', to: 'emergencies#obtain_routes', as: 'get_routes'
  get '/obtain_markers_only_current_emergency/:emergency_id', to: 'emergencies#obtain_markers_only_current_emergency'
  get '/emergencies_get_route/:emergency_id', to: 'emergencies#obtain_route_to_emergency_show', as: 'get_emergency_route'
  get '/emergencies_obtain_markers', to: 'emergencies#obtain_markers'
  get '/emergencies_show_obtain_markers/:emergency_id', to: 'emergencies#obtain_markers_to_emergencies_show'
  get '/schedules_obtain_markers/:schedule_id', to: 'schedules#obtain_markers'
  post '/update_location_from_schedules_show_view/:id', to: 'schedules#update_location_from_schedules_show_view'
  post '/update_location_from_emergencies_show_view/:id', to: 'schedules#update_location_from_emergencies_show_view'
  post '/send_message_to_ambulance/:chat_id', to: 'posts#create'
  post '/find_emergency_after_login/', to: 'schedules#find_emergency'

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :schedules, only: %i[new create index show]
  resources :emergencies, only: %i[new create show index] do
    resources :patients, only: %i[new create]
  end
  resources :chats, only: :show do
    resources :posts, only: :create
  end
  resources :workers
  resources :stocks, only: %i[new create show edit update]

  patch '/emergencies/:id/finish', to: 'emergencies#finish', as: :finish_emergency
  get '/adm', to: 'adms#inicial', as: :home_adm

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/controllers/adms_controller.rb
class AdmsController < ApplicationController
  def inicial
    @adms = policy_scope(User.all)
    authorize current_user
  end
end

app/views/adms/inicial.html.erb
<div class="container ">
  <h1 class="text-vermelho fw-bolder text-center mt-5">Bem vindo Admin</h1>
  <div class="bg-body-tertiary p-5 mt-5 border-radius-60 box-shadow-leve">
    <h1 class="text-vermelho fw-bold"><i class="fa-solid fa-user-plus"></i> Criar usuario</h1>
    <p class="lead text-grey">Ao criar um novo usuário em nosso website, você pode conceder acesso a diferentes áreas e funcionalidades, adaptando-se às necessidades específicas de sua equipe.</p>
    <%# <a class="botao-azul" href="/docs/5.3/components/navbar/" role="button">Novo usuario »</a> %>
  <div class="d-flex gap-4">
    <%= link_to rails_admin.new_path(model_name: 'user'), class: "botao-verde" do %>
      <i class='fa-solid fa-plus'></i> Novo Usuario
    <% end %>
<%= link_to "/admin/user", class: "botao-azul-especial" do %>
  <i class='fa-solid fa-user-pen'></i>Editar/Deletar Usuario
<% end %>
  </div>
  </div>
  <div class="bg-body-tertiary p-5 mt-5 border-radius-60 box-shadow-leve">
    <h1 class="text-vermelho fw-bold"><i class="fa-solid fa-user-nurse"></i> Criar Novo Socorrista</h1>
    <p class="lead text-grey">Adicione novos socorristas ao quadro de serviço</p>
      <div class="d-flex gap-4">
        <%= link_to "<i class='fa-solid fa-plus'></i>  Novo Socorrista".html_safe, new_worker_path , class:"botao-verde" %>
        <!-- Scrollable modal -->
        <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Adicione o Socorrista</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <%= form_with model: @worker do |form| %>

            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name %>
            </div>

            <div class="field">
              <%= form.label :occupation %>
              <%= form.select :occupation,
                  [['Bombeiro', 0], ['Medico', 1], ['Enfermeiro', 2]],
                  { include_blank: "Select Occupation" },
                  { required: true, autofocus: true }
                %>

            </div>

            <div class="actions">
              <%= form.submit %>
            </div>
         <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>


        <%= link_to "<i class='fa-solid fa-user-pen'></i>  Editar/Deletar Socorrista".html_safe, workers_path , class:"botao-azul-especial" %>
    </div>
  </div>
  <div class="bg-body-tertiary p-5 mt-5 border-radius-60 box-shadow-leve">
    <h1 class="text-vermelho fw-bold"><i class="fa-solid fa-chart-simple"></i> Graficos</h1>
    <p class="lead text-grey">Explore nossos poderosos recursos de visualização de dados nesta seção dedicada à demonstração de gráficos. Os gráficos fornecem uma representação visual clara e concisa de informações complexas, permitindo uma compreensão rápida e intuitiva dos dados.</p>
    <%= link_to "/blazer", class: "botao-azul-especial" do %>
      Ver Graficos »
    <% end %>
  </div>
  <div class="bg-body-tertiary p-5 mt-5 mb-5 border-radius-60 box-shadow-leve">
    <h1 class="text-vermelho fw-bold"><i class="fa-solid fa-cubes-stacked"></i> Estoque</h1>
    <p class="lead text-grey">Introduzindo nosso sistema de controle de estoque simples e intuitivo, projetado para simplificar o gerenciamento de inventário e otimizar suas operações. Com uma interface amigável e recursos poderosos, nosso sistema oferece uma solução eficaz para acompanhar e controlar seus produtos de forma eficiente..</p>
    <a class="botao-azul-especial" href="/docs/5.3/components/navbar/" role="button">Ver estoques »</a>
  </div>
</div>
<footer class="py-3 margin-top-100">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2024 SIAS, Inc</p>
  </footer>