config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  get '/emergencies/get_routes', to: 'emergencies#obtain_routes', as: 'get_routes'
  get '/obtain_markers_only_current_emergency/:emergency_id', to: 'emergencies#obtain_markers_only_current_emergency'
  get '/emergencies_get_route/:emergency_id', to: 'emergencies#obtain_route_to_emergency_show', as: 'get_emergency_route'
  get '/emergencies_obtain_markers', to: 'emergencies#obtain_markers'
  get '/emergencies_show_obtain_markers/:emergency_id', to: 'emergencies#obtain_markers_to_emergencies_show'
  get '/schedules_obtain_markers/:schedule_id', to: 'schedules#obtain_markers'
  post '/update_location_from_schedules_show_view/:id', to: 'schedules#update_location_from_schedules_show_view'
  post '/update_location_from_emergencies_show_view/:id', to: 'schedules#update_location_from_emergencies_show_view'
  post '/send_message_to_ambulance/:chat_id', to: 'posts#create'
  post '/find_emergency_after_login/', to: 'schedules#find_emergency'

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :schedules, only: %i[new create index show]
  resources :emergencies, only: %i[new create show index] do
    resources :patients, only: %i[new create]
  end
  resources :chats, only: :show do
    resources :posts, only: :create
  end
  resources :workers
  resources :stocks, only: %i[new create show edit update]

  patch '/emergencies/:id/finish', to: 'emergencies#finish', as: :finish_emergency
  get '/adm', to: 'adms#inicial', as: :home_adm

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  after_create :create_chat_channel_stream
  belongs_to :user
  belongs_to :schedule, optional: true
  belongs_to :hospital, optional: true
  belongs_to :chat, optional: true
  has_many :patients

  validates :n_people, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true

  def create_chat_channel_stream
    ActionCable.server.broadcast(
      "chat_channel",
      { command: "create_stream", emergency_id: self.id }
    )
  end
end

app/controllers/emergencies_controller.rb
require 'json'
require 'date'

class EmergenciesController < ApplicationController
  before_action :authenticate_user!

  def index
    @emergencies = policy_scope(Emergency)
  end

  def new
    @emergency = Emergency.new
    authorize @emergency
  end

  def create
    @emergency = Emergency.new(emergency_params)
    @emergency.user = current_user
    authorize @emergency
    @chat_response = JSON.parse(
      chatgpt_service("Por favor, avalie a seguinte ocorrência: #{@emergency.description}.
        Forneça uma avaliação da gravidade em uma escala de 0 (menos grave) a 20 (mais grave).
        Para a descrição, reescreva a emergência sem acrescentar ou remover informações, porém de forma clara e sucinta e obrigatoriamente com mais de 80 caracteres.
        Informe também o número de pessoas machucadas.
        Para determinar a categoria da ocorrência, atribua o número correspondente à categoria que melhor a descreve, de acordo com as seguintes opções (caso não se enquadre em nenhuma, selecione 'Outros', ou seja, número 11):
        Acidentes de trânsito = 1;
        Mal súbito = 2;
        Ferimentos por queda = 3;
        Parada cardiorrespiratória = 4;
        Intoxicação ou envenenamento = 5;
        Problemas respiratórios = 6;
        Crises hipertensivas = 7;
        Complicações durante a gravidez ou parto = 8;
        Ferimentos por arma branca ou de fogo = 9;
        Reações alérgicas graves = 10;
        Outros = 11;
        Forneça de forma resumida e com até 50 caracteres recomedação/recomendações para a equipe de socorrista do que já deixar preparado para a ocorrência descrita.
        A resposta deve ser uma única hash na seguinte estrutura:
        {\"gravidade\":integer, \"descricao\":string, \"numero_pessoas_machucadas\":integer, \"categoria\":integer, \"recomendacao\":string}.
        Não inclua nenhuma informação adicional além da hash.
        Sempre retorne no formato solicitado e não retorne erro.
        ").call)

    @emergency.gravity = @chat_response["gravidade"]
    @emergency.description = @chat_response["descricao"]
    @emergency.category = @chat_response["categoria"]
    @recomendation = @chat_response["recomendacao"]
    @emergency.time_start = DateTime.now.to_formatted_s(:db)
    if @emergency.save
      find_ambulance(@emergency, @recomendation)
      # find_hospital(@emergency)
      send_to_all_chat(@emergency, @recomendation)
    else
      p "#{@emergency.errors.messages}"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @emergency = Emergency.find(params[:id])
    authorize @emergency
    @schedule = Schedule.find(@emergency.schedule.id)
    @chat = Chat.find(@emergency.chat_id)
    @post = Post.new
    @post.chat = @chat
    @post.user = current_user
    @patient = Patient.new
  end

  def finish
    @emergency = Emergency.find(params[:id])
    schedule = @emergency.schedule
    authorize @emergency
    @emergency.time_end = DateTime.now.to_formatted_s(:db)
    @emergency.end_lat = schedule.current_lat
    @emergency.end_lon = schedule.current_lon
    if @emergency.save
      redirect_to schedule_path(schedule.id)
    else
      render "show", status: :unprocessable_entity
    end
  end

  # >>>>>>>>>>>>>>>>>>>> AJAX ENDPOINTS <<<<<<<<<<<<<<<<<<<<<<

  # endpoint for Mapbox's markers to the central view
  def obtain_markers
    # pundit authorizations
    authorize Emergency.new
    authorize Schedule.new
    authorize Hospital.new

    # markers for not finished emergencies
    emergencies_markers = Emergency.where(time_end: nil).map do |emergency|
      {
        lat: emergency.emergency_lat,
        lng: emergency.emergency_lon,
        marker_html: render_to_string(partial: "emergency"),
        info_window_html: render_to_string(partial: "info_window", locals: { emergency: emergency }),
      }
    end

    # markers for active ambulances
    schedules_markers = Schedule.where(active: true).map do |schedule|
      {
        lat: schedule.current_lat,
        lng: schedule.current_lon,
        marker_html: render_to_string(partial: "schedule_marker"),
        # since each schedule can have more than one emergency, only the unfinished emergency is filtered
        info_window_html: render_to_string(partial: "info_window_schedule", locals: { schedule: schedule, emergency: Emergency.where(schedule_id: schedule, time_end: nil).first })
      }
    end

    # markers for hospitals
    hospitals_markers = Hospital.all.map do |hospital|
      {
        lat: hospital.latitude,
        lng: hospital.longitude,
        marker_html: render_to_string(partial: "hospital_marker"),
        info_window_html: render_to_string(partial: "info_window_hospital", locals: { hospital: hospital })
      }
    end
    render json: { emergencies_markers: emergencies_markers, schedules_markers: schedules_markers, hospitals_markers: hospitals_markers }
  end

  # endpoint for Mapbox's markers from the ambulance view when she already has an emergency
  def obtain_markers_to_emergencies_show
    authorize Emergency.new
    authorize Schedule.new

    # markers for not finished emergencies
    emergencies_markers = Emergency.where(time_end: nil).map do |emergency|
      {
        lat: emergency.emergency_lat,
        lng: emergency.emergency_lon,
        marker_html: render_to_string(partial: "emergency"),
        info_window_html: render_to_string(partial: "info_window", locals: { emergency: emergency }),
      }
    end

    # marker for the active ambulance from the param ID
    schedules_markers = Schedule.joins(:emergencies).where(active: true, emergencies: { id: params[:emergency_id]}).map do |schedule|
      {
        lat: schedule.current_lat,
        lng: schedule.current_lon,
        marker_html: render_to_string(partial: "schedule_marker"),
        # nao estou conseguindo enviar a variavel local emergency para o popup -> problema com o locals ou partials?
        info_window_html: render_to_string(partial: "info_window_schedule", locals: { schedule: schedule, emergency: Emergency.find_by(id: params[:emergency_id]) })
      }
    end
    render json: { emergencies_markers: emergencies_markers, schedules_markers: schedules_markers }
  end

  # endpoint for Mapbox's marker to fit the borders on the current ambulance and the current emergency
  def obtain_markers_only_current_emergency
    authorize Emergency.new
    authorize Schedule.new

    # marker for the active emergency from the param ID
    emergencies_markers = Emergency.where(id: params[:emergency_id]).map do |emergency|
      {
        lat: emergency.emergency_lat,
        lng: emergency.emergency_lon,
        marker_html: render_to_string(partial: "emergency"),
        info_window_html: render_to_string(partial: "info_window", locals: { emergency: emergency }),
      }
    end

    # marker for the active ambulance which is chasing the ambulance from the param ID
    schedules_markers = Schedule.joins(:emergencies).where(active: true, emergencies: { id: params[:emergency_id]}).map do |schedule|
      {
        lat: schedule.current_lat,
        lng: schedule.current_lon,
        marker_html: render_to_string(partial: "schedule_marker"),
        # nao estou conseguindo enviar a variavel local emergency para o popup
        info_window_html: render_to_string(partial: "info_window_schedule", locals: { schedule: schedule, emergency: Emergency.find_by(id: params[:emergency_id]) })
      }
    end
    render json: { emergencies_markers: emergencies_markers, schedules_markers: schedules_markers }
  end

  # endpoint for Mapbox's routes to the central view
  def obtain_routes
    authorize Schedule.new
    authorize Emergency.new
    routes = [] # not necessary, but it's a good practice to declare explicitly
    # select all ambulances that have an ongoing emergency
    schedules = Schedule.joins(:emergencies).where(emergencies: { time_end: nil })
    schedules.each do |schedule|
      emergency = Emergency.find_by(schedule_id: schedule)
      route_coordinates = [
        [schedule.current_lon, schedule.current_lat],  # Start point (schedule)
        [emergency.emergency_lon, emergency.emergency_lat]  # End point (emergency)
      ]
      # creates an array of start and end coordinates for each ongoing route
      routes << route_coordinates
    end

    render json: { routes: routes }
  end

  # endpoint for Mapbox's route to the ambulance view after having an emergency assigned
  def obtain_route_to_emergency_show
    emergency = Emergency.find(params[:emergency_id])
    authorize emergency
    schedule = Schedule.joins(:emergencies).where(emergencies: emergency).first
    authorize schedule
    routes = []
    route_coordinates = [
      [schedule.current_lon, schedule.current_lat],  # Start point (schedule)
      [emergency.emergency_lon, emergency.emergency_lat]  # End point (emergency)
    ]
    # creates an array of start and end coordinates for the ongoing route
    routes << route_coordinates

    render json: { routes: routes }
  end

  # >>>>>>>>>>>>>>>>>>>> AJAX ENDPOINTS END <<<<<<<<<<<<<<<<<<<<<<

  private

  def patient_params
    params.require(:patient).permit(:heart_rate, :blood_pressure, :respiratory_rate, :oxygen_saturation, :consciousness, :pain, :medical_history, :description)
  end

  def emergency_params
    params.require(:emergency).permit(:description, :n_people, :street, :neighborhood, :city, :local_type, :emergency_lat, :emergency_lon)
  end

  def chatroom_params
    params.require(:chatroom).permit(:description, :n_people, :street, :neighborhood, :city, :local_type, :emergency_lat, :emergency_lon)
  end

  def save_without_validation
    save(validate: false)
  end

  # chatgpt
  def chatgpt_service(message)
    ChatgptService.new(message)
  end

  def find_ambulance(emergency, recomendation)
    # restrict the search to only ambulances with emergencies less than 15 or less than the current emergency

app/views/emergencies/_chat_message.html.erb
<p><%= @chat %></p>

app/views/emergencies/_emergency.html.erb
<%= image_tag "emergency_marker.png", height: 20, width: 20, alt: "emergency_marker" %>

app/views/emergencies/_hospital_marker.html.erb
<%= image_tag "hospital.png", height: 20, width: 20, alt: "Ambulance" %>

app/views/emergencies/_info_window_hospital.html.erb
<p><strong>Hospital: </strong><%= hospital.name %></p>

app/views/emergencies/_info_window_schedule.html.erb
<p><strong>Ambulância: </strong><%= schedule.user_id %></p>

app/views/emergencies/_marker.html.erb
<%= image_tag "marker-red.png", height: 40, width: 40, alt: "Red cross" %>

app/views/emergencies/_post.html.erb
<div id="post-<%= post.id %>">
  <small>
    <strong>Central: <%= post.user.id %></strong>
    <i><%= post.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= post.content %></p>
</div>

app/views/emergencies/index.html.erb
<ul>
  <% @emergencies.each do |emergency| %>
    <li><%= emergency.description %></li>
  <% end %>
</ul>

app/views/emergencies/new.html.erb
<div class="p-3">
<h1 class="fw-bolder text-vermelho text-center py-2">Central de Atendimento</h1>
  <div class="container mt-5">
  <div class="bg-body-tertiary p-5 border-radius-60 box-shadow-leve">

    <div class="display-para-flex mb-3">
      <div class="mapa-pegando-emergencia border-radius-24">
        <div id='map' style='width: 100%; height: 400px;' class="border-radius-24 box-shadow-leve"
          data-controller="map"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" ></div>
      </div>
      <div class="todas-ocorrencias ms-4 border-radius-24">
        <div id='map-all' style='width: 100%; height: 400px;' class="border-radius-24 box-shadow-leve"
          data-controller="map-all"
          data-map-all-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
          data-map-all-emergencies-markers-value="<%= @emergencies_markers.to_json %>"
          data-map-all-schedules-markers-value="<%= @schedules_markers.to_json %>"
          data-map-all-hospitals-markers-value="<%= @hospitals_markers.to_json %>" ></div>
      </div>
    </div>
<div class="w-100 text-azul" data-controller="reset-emergency-form">
    <%= simple_form_for @emergency do |f| %>
      <div class="row w-100">
        <div class="col">
          <%= f.input :street, label: "<i class='fa-solid fa-road '></i>  Rua e número".html_safe, input_html: { data: { info_transfer_target: "streetOutput" } }, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
        <div class="col">
          <%= f.input :neighborhood, label:"<i class='fa-solid fa-map-location-dot'></i> Bairro".html_safe, input_html: {data: {info_transfer_target:"neighborhoodOutput"}}, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
      </div>
      <div class="row w-100">
        <div class="col">
          <%= f.input :city, label: "<i class='fa-solid fa-city '></i>  Cidade".html_safe, input_html: {data: {info_transfer_target:"cityOutput"}}, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
        <div class="col">
          <%= f.input :local_type, label: "<i class='fa-solid fa-location-dot'></i> Tipo de local".html_safe, input_html: {data: {info_transfer_target:"categoryOutput"}}, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
      </div>
      <div class="row w-100">
        <div class="col">
          <%= f.input :n_people, label: "<i class='fa-solid fa-person-falling-burst'></i> Número de acidentados".html_safe,label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
        <div class="col">
          <%= f.input :emergency_lat, label: "<i class='fa-solid fa-map-pin'></i> Latitude".html_safe, input_html: {data: {info_transfer_target:"latitudeOutput"}}, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
        <div class="col">
          <%= f.input :emergency_lon, label: "<i class='fa-solid fa-map-pin'></i> Longitude".html_safe, input_html: {data: {info_transfer_target:"longitudeOutput"}}, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24" } %>
        </div>
      </div>
      <div class="row w-100" data-controller="character-count">
        <%= f.input :description, label: "<i class='fa-solid fa-pencil'></i> Descrição da ocorrência".html_safe, label_html: { class: "text-azul fw-bold" }, input_html: { class: "box-shadow-leve border-radius-24", data: { action: "keyup->character-count#updateCounter"} }  %>
        <div>
          <p data-character-count-target="counter"></p>
        </div>
      </div>
        <%= f.button :submit, "Criar nova emergência", class:"botao-azul mt-2", remote: true %>
    <% end %>
   </div>
</div>
</div>
</div>

<footer class="py-3">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
  </ul>
  <p class="text-center text-muted">© 2024 SIAS, Inc</p>
</footer>

app/views/emergencies/popup_view.html.erb
<% if @texto_popup.present? %>
  <div id="popup">
    <div class="popup-content">
      <p><%= @texto_popup %></p>
    </div>
  </div>

  <!-- Adicione aqui o código JavaScript/jQuery para exibir o popup -->
  <script>
    // Exibe o popup quando a página é carregada
    document.addEventListener("DOMContentLoaded", function() {
      // Coloque aqui o código para exibir o popup, por exemplo, usando JavaScript/jQuery
      // Por exemplo, usando jQuery:
      // $('#popup').show();
    });
  </script>
<% end %>

app/views/emergencies/show.html.erb
  <div data-controller="class-invisible">
    <div class="background-image-gradient w-100"  data-class-invisible-target="background"></div>
    <div  data-class-invisible-target="classe">
    <div class="body pop-up-emergency ">
      <div class="d-flex card-jairo">
        <div class="alinhar d-flex interno gap-3">
          <h1 class="alinhar text-azul">Voce tem uma nova emergência!</h1>
          <button class="alinhar text-azul" data-action="click->class-invisible#invisible">OK</button>

        </div>
      </div>
    </div>
  </div>
  <div class="nav-tab-bar">
    <ul class="nav nav-tabs nav-fill nav-justified" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="map-tab" data-bs-toggle="tab" data-bs-target="#map" type="button" role="tab" aria-controls="map" aria-selected="true">Mapa</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="paciente-tab" data-bs-toggle="tab" data-bs-target="#paciente" type="button" role="tab" aria-controls="paciente" aria-selected="false">Paciente</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="chat-tab" data-bs-toggle="tab" data-bs-target="#chat" type="button" role="tab" aria-controls="chat" aria-selected="false">Chat</button>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="map" role="tabpanel" aria-labelledby="map-tab">
        <div class="centraliziation-of-the-map"  data-controller="emergencies-show-view-geolocation">
          <div class="" id='map' style='width: 100%; height: 100%;'
            data-controller="map-mobile-show-emergency"
            data-map-mobile-show-emergency-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" ></div>
        </div>
        <div class="emergency-show">
          <!-- Button trigger modal -->
          <div class="button-finish-emergency">
            <button type="button" class="btn btn-warning button-finish" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Finalizar
            </button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Ambulância #<%= @schedule.id %></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    Gostaria de finalizar a ocorrência #<%= @emergency.id %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <%= button_to 'Continuar', finish_emergency_path(@emergency.id), method: :patch, class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="paciente" role="tabpanel" aria-labelledby="Paciente-tab" data-controller="reset-patient-form">
        <%= render partial: "patients/form_patient", locals: {emergency: @emergency, patient: @patient} %>
      </div>

      <div class="tab-pane fade" id="chat" role="tabpanel" aria-labelledby="chat-tab">
        <div class="container chat"
          data-controller="chat-subscription"
          data-chat-subscription-chat-id-value="<%= @chat.id %>" >
          <h3><%= @chat.name %></h3>

          <div class="posts" data-chat-subscription-target="posts">
            <% @chat.posts.each do |post| %>
              <%= render "emergencies/post", post: post %>
            <% end %>
          </div>
          <%= simple_form_for [@chat, @post], url: "/send_message_to_ambulance/#{@chat.id}",
            html: {class: "d-flex",
            data: { chat_subscription_target: 'form' }} do |f| %>
              <%= f.input :content,
                label: false,
                placeholder: "Post ##{@chat.name}",
                wrapper_html: {class: "flex-grow-1"} %>
              <%= f.submit "Send", class: "btn btn-primary mb-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>