config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  get '/emergencies/get_routes', to: 'emergencies#obtain_routes', as: 'get_routes'
  get '/obtain_markers_only_current_emergency/:emergency_id', to: 'emergencies#obtain_markers_only_current_emergency'
  get '/emergencies_get_route/:emergency_id', to: 'emergencies#obtain_route_to_emergency_show', as: 'get_emergency_route'
  get '/emergencies_obtain_markers', to: 'emergencies#obtain_markers'
  get '/emergencies_show_obtain_markers/:emergency_id', to: 'emergencies#obtain_markers_to_emergencies_show'
  get '/schedules_obtain_markers/:schedule_id', to: 'schedules#obtain_markers'
  post '/update_location_from_schedules_show_view/:id', to: 'schedules#update_location_from_schedules_show_view'
  post '/update_location_from_emergencies_show_view/:id', to: 'schedules#update_location_from_emergencies_show_view'
  post '/send_message_to_ambulance/:chat_id', to: 'posts#create'
  post '/find_emergency_after_login/', to: 'schedules#find_emergency'

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :schedules, only: %i[new create index show]
  resources :emergencies, only: %i[new create show index] do
    resources :patients, only: %i[new create]
  end
  resources :chats, only: :show do
    resources :posts, only: :create
  end
  resources :workers
  resources :stocks, only: %i[new create show edit update]

  patch '/emergencies/:id/finish', to: 'emergencies#finish', as: :finish_emergency
  get '/adm', to: 'adms#inicial', as: :home_adm

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :first_schedules, class_name: 'Schedule', foreign_key: 'worker1_id'
  has_many :second_schedules, class_name: 'Schedule', foreign_key: 'worker2_id'

  validates :name, presence: true
  validates :occupation, presence: true
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :authenticate_user!

  def index
    @workers = Worker.all
    authorize @workers
  end

  def show
    @worker = Worker.find(params[:id])
    authorize @worker
  end

  def update
    @worker = Worker.find(params[:id])
    authorize @worker

    if @worker.update(worker_params)
      redirect_to workers_path, notice: 'Worker was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @worker = Worker.find(params[:id])
    authorize @worker
    @worker.destroy
    redirect_to workers_path, notice: 'Worker was successfully deleted.'
  end

  def new
    @worker = Worker.new
    authorize @worker
  end

  def create

    @worker = Worker.new(worker_params)
    authorize @worker

    if @worker.save
      redirect_to home_adm_path, notice: 'Worker was successfully created.'
    else
      render :new
    end
  end

  private

  def worker_params
    params.require(:worker).permit(:name, :occupation)
  end
end

app/views/workers/index.html.erb
<h1>Socorrista</h1>
<ul>
  <% @workers.each do |worker| %>
    <li>
    <div class="d-flex gap-3 my-2">
      <%= worker.name %>
      <%= link_to "<i class='fa-solid fa-user-pen'></i>  Editar Socorrista".html_safe, worker_path(worker) , class:"botao-azul-especial" %>
      <%= link_to "<i class='fa-solid fa-x'></i>  Deletar Socorrista".html_safe, worker_path(worker),  data: { "turbo-method": :delete }, class: "botao-vermelho" %>
    </div>

    </li>
  <% end %>
</ul>
<%= link_to "voltar", home_adm_path, class: "back-link" %>

app/views/workers/new.html.erb
<div class="container">
  <h1>Adicionar novo Usuario</h1>
  <%= form_with model: @worker do |form| %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :occupation %>
       <%= form.select :occupation,
          [['Bombeiro', 0], ['Medico', 1], ['Enfermeiro', 2]],
          { include_blank: "Select Occupation" },
          { required: true, autofocus: true }
        %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  <%= link_to "voltar", home_adm_path, class: "back-link" %>
</div>

app/views/workers/show.html.erb
<%= form_with model: @worker do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<div class="field">
  <%= form.label :occupation %>
  <%= form.collection_select :occupation, User::OCCUPATION_OPTIONS, :last, :first, prompt: "Select Occupation" %>
</div>

  <div class="actions">
    <%= form.submit "Update Worker", class: "btn btn-primary" %>
  </div>
<% end %>