config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  get '/emergencies/get_routes', to: 'emergencies#obtain_routes', as: 'get_routes'
  get '/obtain_markers_only_current_emergency/:emergency_id', to: 'emergencies#obtain_markers_only_current_emergency'
  get '/emergencies_get_route/:emergency_id', to: 'emergencies#obtain_route_to_emergency_show', as: 'get_emergency_route'
  get '/emergencies_obtain_markers', to: 'emergencies#obtain_markers'
  get '/emergencies_show_obtain_markers/:emergency_id', to: 'emergencies#obtain_markers_to_emergencies_show'
  get '/schedules_obtain_markers/:schedule_id', to: 'schedules#obtain_markers'
  post '/update_location_from_schedules_show_view/:id', to: 'schedules#update_location_from_schedules_show_view'
  post '/update_location_from_emergencies_show_view/:id', to: 'schedules#update_location_from_emergencies_show_view'
  post '/send_message_to_ambulance/:chat_id', to: 'posts#create'
  post '/find_emergency_after_login/', to: 'schedules#find_emergency'

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :schedules, only: %i[new create index show]
  resources :emergencies, only: %i[new create show index] do
    resources :patients, only: %i[new create]
  end
  resources :chats, only: :show do
    resources :posts, only: :create
  end
  resources :workers
  resources :stocks, only: %i[new create show edit update]

  patch '/emergencies/:id/finish', to: 'emergencies#finish', as: :finish_emergency
  get '/adm', to: 'adms#inicial', as: :home_adm

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :posts
  has_many :emergencies
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  after_create :create_chat_channel_stream
  belongs_to :user
  belongs_to :schedule, optional: true
  belongs_to :hospital, optional: true
  belongs_to :chat, optional: true
  has_many :patients

  validates :n_people, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true

  def create_chat_channel_stream
    ActionCable.server.broadcast(
      "chat_channel",
      { command: "create_stream", emergency_id: self.id }
    )
  end
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :emergencies
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :emergency
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  attr_accessor :worker1_name, :worker2_name

  belongs_to :worker1, class_name: 'Worker'
  belongs_to :worker2, class_name: 'Worker'
  belongs_to :user
  has_many :emergencies

  validates :worker1_id, presence: true, numericality: { greater_than: 0 }
  validates :worker2_id, presence: true, numericality: { greater_than: 0 }
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules
  has_many :emergencies
  has_many :stocks

  OCCUPATION_OPTIONS = [
    ["Bombeiro", 0],
    ["Enfermeiro", 1],
    ["Médico", 2],
    ["Motorista", 3]
   ].freeze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :first_schedules, class_name: 'Schedule', foreign_key: 'worker1_id'
  has_many :second_schedules, class_name: 'Schedule', foreign_key: 'worker2_id'

  validates :name, presence: true
  validates :occupation, presence: true
end

app/controllers/adms_controller.rb
class AdmsController < ApplicationController
  def inicial
    @adms = policy_scope(User.all)
    authorize current_user
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def create
    @chat = Chat.new
  end

  def show
    @chat = Chat.find(params[:id])
    @post = Post.new
    authorize @chat
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(1)
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    authorize @message
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
    else
      render 'chatrooms/show'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :botao]

  def home
  end

  def botao
    @schedule = Schedule.find_by(user_id: current_user.id)
    @emergency = Emergency.where(id: @schedule.id).where("emergencies.time_end IS NULL")
    @emergency = @emergency[0]

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create

    @chat = Chat.find(params[:chat_id])
    @post = Post.new(post_params)
    @post.chat = @chat
    @post.user = current_user
    authorize @post
    if @post.save
      ChatChannel.broadcast_to(
        @chat,
        render_to_string(partial: "post", locals: {post: @post})
      )
      head :ok
    else
      render "emergencies/chats/show", status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def new
    @stock = Stock.new
    @stock.user = current_user
    authorize @stock
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.user = current_user
    authorize @stock

    if @stock.save!
      redirect_to @stock
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @stock = Stock.find(params[:id])
    authorize @stock
  end

  def edit
    @stock = Stock.find(params[:id])
    authorize @stock
  end

  def update
    @stock = Stock.find(params[:id])
    @stock.update(stock_params)
    authorize @stock
    if @stock.update(stock_params)
      redirect_to stock_path(@stock)
    else
      render :edit, status: unprocessable_entity
    end
  end

  private

  def stock_params
    params.require(:stock).permit(:tesoura, :luvas, :pinça, :esparadrapo, :alcool, :gaze_esterilizada, :atadura, :bandagens, :medicamentos_basicos)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :authenticate_user!

  def index
    @workers = Worker.all
    authorize @workers
  end

  def show
    @worker = Worker.find(params[:id])
    authorize @worker
  end

  def update
    @worker = Worker.find(params[:id])
    authorize @worker

    if @worker.update(worker_params)
      redirect_to workers_path, notice: 'Worker was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @worker = Worker.find(params[:id])
    authorize @worker
    @worker.destroy
    redirect_to workers_path, notice: 'Worker was successfully deleted.'
  end

  def new
    @worker = Worker.new
    authorize @worker
  end

  def create

    @worker = Worker.new(worker_params)
    authorize @worker

    if @worker.save
      redirect_to home_adm_path, notice: 'Worker was successfully created.'
    else
      render :new
    end
  end

  private

  def worker_params
    params.require(:worker).permit(:name, :occupation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIAS - Sistema de Auxílio aos Socorristas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('logo_sias_blue.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v3.1.0/mapbox-gl.js'></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v5.0.0/mapbox-gl-directions.js"></script>

    <link href='https://api.mapbox.com/mapbox-gl-js/v3.1.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%unless(request.fullpath == schedules_path) || (request.fullpath == new_schedule_path) %>
      <%= render "shared/navbar" %>
   <% end %>

    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
      <% if request.fullpath == new_emergency_path%>
        <div class="navbar-brand">
          <%= image_tag "SIAS-CREME.png" %>
        </div>
      <% else %>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "SIAS-CREME.png" %>
        <% end %>
      <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item dropdown">
          <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.admin  %>
              <p class="m-0 p-0">Olá ADMIN</p>
            <% elsif current_user.central %>
              <p>Olá CENTRAL</p>
            <% else %>
              <p><em>Olá, SOCORRISTAS</em></p>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end background-color-azul drop-jairo" aria-labelledby="navbarDropdown">
              <%= link_to "<i class='fa-solid fa-right-from-bracket'></i> Log out".html_safe, destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/users/sign_in" class="botão-login-navbar">Entrar</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>